// Lista enxuta das principais cidades brasileiras (capitais + grandes
// regiões metropolitanas) para autocomplete do campo "Cidade ou região
// de retirada". Não depende de API externa — offline e instantâneo.
// Formato: "Cidade - UF".

export const BRAZILIAN_CITIES: string[] = [
  "São Paulo - SP",
  "Guarulhos - SP",
  "Campinas - SP",
  "São Bernardo do Campo - SP",
  "Santo André - SP",
  "Osasco - SP",
  "Sorocaba - SP",
  "Ribeirão Preto - SP",
  "São José dos Campos - SP",
  "Santos - SP",
  "Rio de Janeiro - RJ",
  "São Gonçalo - RJ",
  "Duque de Caxias - RJ",
  "Nova Iguaçu - RJ",
  "Niterói - RJ",
  "Belo Horizonte - MG",
  "Contagem - MG",
  "Uberlândia - MG",
  "Juiz de Fora - MG",
  "Betim - MG",
  "Curitiba - PR",
  "Londrina - PR",
  "Maringá - PR",
  "Porto Alegre - RS",
  "Caxias do Sul - RS",
  "Canoas - RS",
  "Salvador - BA",
  "Feira de Santana - BA",
  "Vitória da Conquista - BA",
  "Recife - PE",
  "Jaboatão dos Guararapes - PE",
  "Fortaleza - CE",
  "Caucaia - CE",
  "Brasília - DF",
  "Goiânia - GO",
  "Aparecida de Goiânia - GO",
  "Manaus - AM",
  "Belém - PA",
  "Ananindeua - PA",
  "São Luís - MA",
  "Natal - RN",
  "João Pessoa - PB",
  "Maceió - AL",
  "Aracaju - SE",
  "Teresina - PI",
  "Campo Grande - MS",
  "Cuiabá - MT",
  "Florianópolis - SC",
  "Joinville - SC",
  "Blumenau - SC",
  "Vitória - ES",
  "Vila Velha - ES",
  "Palmas - TO",
  "Porto Velho - RO",
  "Macapá - AP",
  "Rio Branco - AC",
  "Boa Vista - RR",
];
